python train.py \
  -b 1 \
  -e 40 \
  -l 0.0001 \
  -r 10 \
  -n 'test_Varnet/final/swinunet_2' \
  -t '/storage/junsoo/train/' \
  -v '/storage/junsoo/val/' \
  --use-transformer \
  --kspace-augment-config configs/kspace_mask_augment_2_exp.yaml \
  --resume /home/junsoo/result/test_Varnet/final/swinunet/checkpoints/best_model.pt