python train.py \
  -b 1 \
  -e 40 \
  -l 0.0001 \
  -r 10 \
  -n 'test_Varnet/result/unet_2' \
  -t '/storage/junsoo/train/' \
  -v '/storage/junsoo/val/' \
  --chans 18 \
  --kspace-augment-config configs/kspace_mask_augment_2.yaml \
  --resume /home/junsoo/result/test_Varnet/final/unet/checkpoints/model_epoch_8.pt