# MRAugment Paper Settings - 1% Data Configuration
# Matches original singlecoil_train1_DA.yaml settings
# NOTE: Some transforms disabled due to dimension constraints in current setup

# Core augmentation settings (Original MRAugment)
aug_on: true
aug_strength: 0.60             # Strong for limited data
aug_schedule: "exp"            # Exponential decay
aug_delay: 0                   # Start immediately
aug_exp_decay: 5.0             # Medium decay rate

# Transform weights (Partially enabled for compatibility)
# NOTE: Translation is pixel-preserving and safe to enable
aug_weight_translation: 1.0   # Original: 1.0 - ENABLED (pixel-preserving)
aug_weight_rotation: 0.0       # Original: 0.5 - DISABLED for now  
aug_weight_scaling: 0.0        # Original: 1.0 - DISABLED for now
aug_weight_shearing: 0.0       # Original: 1.0 - DISABLED for now
aug_weight_rot90: 0.0          # Original: 0.5 - DISABLED (swaps dimensions)
aug_weight_fliph: 0.5          # Original: 0.5 - ENABLED
aug_weight_flipv: 0.5          # Original: 0.5 - ENABLED

# Transform parameters (Original MRAugment values)
aug_max_translation_x: 0.125  # 12.5% - original value
aug_max_translation_y: 0.08   # 8% - original value
aug_max_rotation: 180.0       # 180° - original value
aug_max_scaling: 0.25         # 25% - original value
aug_max_shearing_x: 15.0      # 15° - original value
aug_max_shearing_y: 15.0      # 15° - original value

# Processing options (Original MRAugment)
aug_upsample: false           # Disabled for compatibility
aug_upsample_factor: 2        # Original value
aug_upsample_order: 1         # Original value  
aug_interpolation_order: 1    # Original value

# Training parameters (for reference)
# max_epochs: 1000            # Original training length
# lr: 0.0003                  # Original learning rate