# MRAugment Paper Settings - Full Strength (Research Version)
# This matches the original paper exactly but may cause dimension issues
# Use only when dimension-preserving fixes are implemented

# Core augmentation settings (Exact Original)
aug_on: true
aug_strength: 0.60             # Original paper strength
aug_schedule: "exp"            # Exponential decay
aug_delay: 0                   # Start immediately  
aug_exp_decay: 5.0             # Original decay rate

# Transform weights (FULL ORIGINAL - may cause issues!)
aug_weight_translation: 1.0   # ⚠️ May change dimensions
aug_weight_rotation: 0.5       # ⚠️ May change dimensions
aug_weight_scaling: 1.0        # ⚠️ May change dimensions
aug_weight_shearing: 1.0       # ⚠️ May change dimensions 
aug_weight_rot90: 0.5          # ⚠️ Will swap H/W dimensions
aug_weight_fliph: 0.5          # ✅ Safe
aug_weight_flipv: 0.5          # ✅ Safe

# Transform parameters (Exact Original)
aug_max_translation_x: 0.125  # 12.5% of width
aug_max_translation_y: 0.08   # 8% of height
aug_max_rotation: 180.0       # Full 180° rotation
aug_max_scaling: 0.25         # 25% scale variation
aug_max_shearing_x: 15.0      # 15° shearing X
aug_max_shearing_y: 15.0      # 15° shearing Y

# Processing options (Exact Original)
aug_upsample: true            # ⚠️ May cause memory issues
aug_upsample_factor: 2        # 2x upsampling
aug_upsample_order: 1         # Bilinear
aug_interpolation_order: 1    # Bilinear

# WARNING: This config replicates original MRAugment exactly
# but may cause tensor dimension mismatches in current setup.
# Use augment_mraugment_1pct.yaml for safe version.