# Basic MRI Data Augmentation Configuration  
# Balanced augmentation settings recommended for most scenarios

# Core augmentation settings
aug_on: true
aug_strength: 0.6
aug_schedule: "exp"
aug_delay: 0
aug_exp_decay: 5.0

# Transform weights (probability of applying each transform)
aug_weight_translation: 1.0
aug_weight_rotation: 0.5
aug_weight_scaling: 1.0
aug_weight_shearing: 0.0
aug_weight_rot90: 0.5
aug_weight_fliph: 0.5
aug_weight_flipv: 0.5

# Transform parameters
aug_max_translation_x: 0.125  # 12.5% of image width
aug_max_translation_y: 0.08   # 8% of image height  
aug_max_rotation: 15.0        # 15 degrees
aug_max_scaling: 0.15         # 15% scale variation
aug_max_shearing_x: 0.0
aug_max_shearing_y: 0.0

# Processing options
aug_upsample: true
aug_upsample_factor: 2
aug_upsample_order: 1
aug_interpolation_order: 1