# MRAugment Paper Settings - 10% Data Configuration  
# Matches original singlecoil_train10_DA.yaml settings
# Conservative version for current system compatibility

# Core augmentation settings (Original MRAugment)
aug_on: true
aug_strength: 0.55             # Medium-strong for moderate data
aug_schedule: "exp"            # Exponential decay
aug_delay: 0                   # Start immediately
aug_exp_decay: 5.0             # Medium decay rate

# Transform weights (Conservative version)
aug_weight_translation: 0.0   # Original: 1.0 - ENABLED (pixel-preserving)
aug_weight_rotation: 0.0       # Original: 0.5 - DISABLED
aug_weight_scaling: 0.0        # Original: 1.0 - DISABLED 
aug_weight_shearing: 0.0       # Original: 1.0 - DISABLED
aug_weight_rot90: 0.0          # Original: 0.5 - DISABLED
aug_weight_fliph: 0.5          # Original: 0.5 - ENABLED
aug_weight_flipv: 0.5          # Original: 0.5 - ENABLED

# Transform parameters (Original values for future use)
aug_max_translation_x: 0.125
aug_max_translation_y: 0.08
aug_max_rotation: 180.0
aug_max_scaling: 0.25
aug_max_shearing_x: 15.0
aug_max_shearing_y: 15.0

# Processing options
aug_upsample: false
aug_upsample_factor: 2
aug_upsample_order: 1
aug_interpolation_order: 1

# Training parameters (for reference)
# max_epochs: 500             # Original training length
# lr: 0.0003                  # Original learning rate