# K-space Domain Augmentation Configuration
# Mathematically consistent augmentation that preserves k-space/image relationship

# Base augmentation probabilities (scaled by strength schedule)
prob_hflip: 0.4          # Base probability of horizontal flip
prob_vflip: 0.4          # Base probability of vertical flip  
prob_shift: 0.0          # Base probability of circular shift (plane movement)

# Shift parameters
max_shift_fraction: 0.0  # Maximum shift as fraction of image size (5%)

# Scheduling parameters (following MRAugment design)
aug_strength: 1.0         # Maximum augmentation strength (0.0-1.0)
aug_schedule: 'exp'       # Schedule type: 'constant', 'ramp', 'exp'
aug_delay: 0              # Number of epochs to delay augmentation start
max_epochs: 40            # Total number of training epochs (for scheduling)
aug_exp_decay: 5.0        # Exponential decay coefficient (for 'exp' schedule)

# Random seed for reproducibility (optional)
seed: 42